[build]
  base = "server/client"               
  command = "npm run build"
  publish = "server/client/dist"       # ajusta si usas "client/dist" o "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
